import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProviderProvider from "@/provider/QueryClientProviderProvider";
import MapProvider from "@/provider/MapContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProviderProvider>
        <MapProvider>
          <body className={inter.className}>{children}</body>
        </MapProvider>
      </QueryClientProviderProvider>
    </html>
  );
}
